//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAlex.MathCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAlex.MathCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array size is too large..
        /// </summary>
        internal static string EXC_ARRAY_SIZE_IS_TOO_LARGE {
            get {
                return ResourceManager.GetString("EXC_ARRAY_SIZE_IS_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast object of type &apos;{0}&apos; to type &apos;{1}&apos;.
        /// </summary>
        internal static string EXC_INVALID_CAST {
            get {
                return ResourceManager.GetString("EXC_INVALID_CAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of the complex number..
        /// </summary>
        internal static string EXC_INVALID_FORMAT_COMPLEX {
            get {
                return ResourceManager.GetString("EXC_INVALID_FORMAT_COMPLEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} contains an invalid character &apos;{1}&apos;.
        /// </summary>
        internal static string EXC_INVALID_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("EXC_INVALID_NUMBER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of iteration is too much..
        /// </summary>
        internal static string EXC_ITERATION_COUNT_IS_TOO_MUCH {
            get {
                return ResourceManager.GetString("EXC_ITERATION_COUNT_IS_TOO_MUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format of complex polynomial..
        /// </summary>
        internal static string EXC_POLY_INCCORECT_FORMAT {
            get {
                return ResourceManager.GetString("EXC_POLY_INCCORECT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial can&apos;t contains variables with different names..
        /// </summary>
        internal static string EXC_POLY_MISMATCH_VAR_NAMES {
            get {
                return ResourceManager.GetString("EXC_POLY_MISMATCH_VAR_NAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not be empty..
        /// </summary>
        internal static string EXC_STRING_NOT_EMPTY {
            get {
                return ResourceManager.GetString("EXC_STRING_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String should not be null reference..
        /// </summary>
        internal static string EXC_STRING_NOT_NULL {
            get {
                return ResourceManager.GetString("EXC_STRING_NOT_NULL", resourceCulture);
            }
        }
    }
}
